# Generated by Django 4.2.7 on 2023-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_user_data_bln_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='phone_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
