# Generated by Django 4.2.7 on 2023-11-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0008_order_status_products_description_products_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='delivery_app.user_data'),
        ),
        migrations.AlterField(
            model_name='order_master',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delevery_agent', to='delivery_app.user_data'),
        ),
    ]
