# Generated by Django 4.2.7 on 2023-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0009_order_master_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='total_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
