# Generated by Django 4.2.7 on 2023-11-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(default='test')),
                ('role_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.role_master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='role_url_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('role_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.role_master')),
            ],
        ),
    ]
