# Generated by Django 4.2.7 on 2023-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_remove_user_data_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
    ]
