# Generated by Django 4.2.7 on 2023-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='int_status',
            field=models.IntegerField(default=1),
        ),
    ]
