# Generated by Django 4.2.7 on 2023-11-20 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_products_int_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('total_amt', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('int_status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_master_created_by', to='delivery_app.user_data')),
                ('delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delevery_agent', to='delivery_app.user_data')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_master_modified_by', to='delivery_app.user_data')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delevery_agent', to='delivery_app.order_status')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('int_status', models.IntegerField(default=1)),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.order_master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.products')),
            ],
        ),
    ]
