# Generated by Django 4.2.7 on 2023-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0010_alter_order_master_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_url_permission',
            name='bln_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role_url_permission',
            name='bln_get',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role_url_permission',
            name='bln_patch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role_url_permission',
            name='bln_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role_url_permission',
            name='bln_put',
            field=models.BooleanField(default=True),
        ),
    ]
