# Generated by Django 4.2.7 on 2023-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_role_url_permission_bln_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
